-- ============================================================
-- GPS Leadership Solutions — Migration v13
-- 14-Day Executive Leadership Diagnostic — Full Schema
--
-- Run in Supabase SQL Editor. Safe to re-run: all statements
-- use IF NOT EXISTS / IF EXISTS guards.
--
-- Creates:
--   1. clients.client_type       — coaching | diagnostic_only | alumni | both
--   2. diagnostics               — one row per diagnostic engagement
--   3. diagnostic_raters         — one row per invited rater (incl. self)
--   4. diagnostic_responses      — one row per question per rater
--   5. diagnostic_question_overrides — per-diagnostic question edits
--   6. diagnostic_report_drafts  — AI-generated report versions
--   7. ghl_export_view           — safe export view for GoHighLevel
--   8. Indexes
-- ============================================================


-- ── 1. clients — add client_type ─────────────────────────────────────────────
--
-- coaching      : active coaching engagement (existing portal users)
-- diagnostic_only : paid diagnostic, no coaching contract
-- alumni        : completed GPS workshop, portal access for 90-day plan only
-- both          : has both an active diagnostic and active coaching

ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS client_type TEXT NOT NULL DEFAULT 'coaching'
  CHECK (client_type IN ('coaching','diagnostic_only','alumni','both'));

COMMENT ON COLUMN clients.client_type IS
  'Determines which features are active and how the client appears in the coach portal.
   coaching = active coaching engagement.
   diagnostic_only = paid diagnostic, no coaching.
   alumni = post-workshop portal access only.
   both = active coaching + active diagnostic.';


-- ── 2. diagnostics — core diagnostic record ──────────────────────────────────
--
-- One row per engagement. Stores all metadata, pipeline status, self-report
-- succession responses, Claude-generated custom question, and plan status.

CREATE TABLE IF NOT EXISTS diagnostics (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Client link (nullable: diagnostic client may not be a coaching client yet)
  client_id                 UUID REFERENCES clients(id) ON DELETE SET NULL,

  -- Client identity (denormalized so diagnostic survives if client row is deleted)
  client_name               TEXT NOT NULL,
  client_email              TEXT NOT NULL,
  client_title              TEXT,
  client_org                TEXT,

  -- Tier and delivery mode
  tier                      TEXT NOT NULL DEFAULT 'standard'
                            CHECK (tier IN ('standard','pro')),
  email_delivery_mode       TEXT NOT NULL DEFAULT 'gps_sends'
                            CHECK (email_delivery_mode IN ('gps_sends','client_sends')),
  -- gps_sends   = portal auto-sends tokenized invite emails
  -- client_sends = portal generates email templates; Alex or client forwards manually

  -- Pipeline status (mirrors 8-milestone pipeline shown to leader)
  status                    TEXT NOT NULL DEFAULT 'setup'
                            CHECK (status IN (
                              'setup',               -- Step 1: Intake not complete
                              'intake_complete',     -- Step 1 done: intake call complete
                              'self_assessment_pending', -- Step 2: waiting on leader
                              'self_assessment_complete',-- Step 2 done: invites can go out
                              'survey_open',         -- Step 4: survey window active
                              'survey_closed',       -- Step 5: data locked
                              'report_draft',        -- Step 6: report being built
                              'report_final',        -- Step 6 done: report finalized
                              'debrief_complete',    -- Step 7 done
                              'plan_active'          -- Step 8: 90-day plan locked
                            )),

  -- Survey window
  start_date                DATE,   -- survey opens
  close_date                DATE,   -- survey closes (auto = start + 7 days)

  -- Intake
  intake_notes              TEXT,
  intake_transcript_url     TEXT,
  intake_completed_at       TIMESTAMPTZ,

  -- Self-report succession responses (Section E — stored here, not in responses table)
  -- Stored on the diagnostic record because they drive Claude custom question generation
  -- and are referenced in the report separately from rater data.
  self_three_year_vision          TEXT,
  self_future_self_capabilities   TEXT,
  self_immediate_successor_view   TEXT,
  self_successor_candidates       TEXT,
  self_successor_development_actions TEXT,
  self_assessment_completed_at    TIMESTAMPTZ,

  -- Custom rater question (Section G, G1) — generated by Claude from self_three_year_vision
  custom_g1_question        TEXT,
  custom_g1_generated_at    TIMESTAMPTZ,

  -- Rater invite tracking
  raters_finalized_at       TIMESTAMPTZ,  -- Alex approved rater list
  invites_sent_at           TIMESTAMPTZ,  -- bulk invite emails sent

  -- Survey window management
  survey_closed_at          TIMESTAMPTZ,  -- actual close (may differ from close_date)
  alert_t2_sent_at          TIMESTAMPTZ,  -- T-2 day alert (dedupe guard)

  -- Report
  report_generated_at       TIMESTAMPTZ,
  report_finalized_at       TIMESTAMPTZ,

  -- Debrief & 90-day plan
  debrief_completed_at      TIMESTAMPTZ,
  plan_status               TEXT NOT NULL DEFAULT 'not_started'
                            CHECK (plan_status IN ('not_started','draft','active','locked')),
  plan_draft_content        TEXT,
  plan_locked_at            TIMESTAMPTZ,
  plan_lock_source          TEXT CHECK (plan_lock_source IN ('auto_24h','manual')),
  -- auto_24h = cron locked it 24h after debrief_completed_at
  -- manual   = Alex or client locked it explicitly

  -- Leader portal access token (used in URL: /diagnostic-leader.html?token=...)
  leader_token              TEXT UNIQUE DEFAULT gen_random_uuid()::TEXT,
  leader_token_last_used_at TIMESTAMPTZ,

  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE diagnostics ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read diagnostics"   ON diagnostics;
DROP POLICY IF EXISTS "Allow anon insert diagnostics" ON diagnostics;
DROP POLICY IF EXISTS "Allow anon update diagnostics" ON diagnostics;
CREATE POLICY "Allow anon read diagnostics"   ON diagnostics FOR SELECT USING (true);
CREATE POLICY "Allow anon insert diagnostics" ON diagnostics FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update diagnostics" ON diagnostics FOR UPDATE USING (true);

COMMENT ON TABLE diagnostics IS
  '14-Day Executive Leadership Diagnostic — one row per engagement.
   Self-report succession responses stored here (Section E) because they
   drive Claude custom question generation before rater invites go out.
   All other survey responses are in diagnostic_responses.';

COMMENT ON COLUMN diagnostics.leader_token IS
  'UUID token used in the leader portal URL. Never expose to raters.
   Example URL: /diagnostic-leader.html?token=<leader_token>';

COMMENT ON COLUMN diagnostics.alert_t2_sent_at IS
  'Timestamp when T-2 day low-response alert was sent to Alex.
   Non-null = alert already fired. Cron checks this before sending to prevent duplicates.
   Fires when total completions < 7 two days before close_date.';

COMMENT ON COLUMN diagnostics.plan_lock_source IS
  'auto_24h = cron locked plan 24 hours after debrief_completed_at.
   manual = explicitly locked by Alex or client.';


-- ── 3. diagnostic_raters — invited raters ────────────────────────────────────
--
-- One row per invited rater, including the leader themselves (is_self = true).
-- The leader self-assessment uses a separate token that lands them in self-report mode.
-- Rater tokens are UUID strings appended as ?token=... in the survey URL.

CREATE TABLE IF NOT EXISTS diagnostic_raters (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  diagnostic_id   UUID NOT NULL REFERENCES diagnostics(id) ON DELETE CASCADE,

  name            TEXT NOT NULL,
  email           TEXT NOT NULL,
  relationship    TEXT NOT NULL
                  CHECK (relationship IN (
                    'Self',
                    'Direct Report',
                    'Peer',
                    'Supervisor',
                    'Internal Partner',
                    'External Partner',
                    'Board / Investor',
                    'Key Customer'
                  )),

  -- Survey access token (used in URL: /diagnostic-survey.html?token=...)
  token           TEXT UNIQUE NOT NULL DEFAULT gen_random_uuid()::TEXT,

  is_self         BOOLEAN NOT NULL DEFAULT FALSE,
  -- TRUE only for the leader's own self-assessment row
  -- Self row is created automatically when invites are sent

  invited_at      TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,   -- set when survey is submitted

  -- Reminder tracking (mirrors existing survey_tokens pattern)
  reminder_1_sent_at  TIMESTAMPTZ,
  reminder_2_sent_at  TIMESTAMPTZ,
  email_bounced       BOOLEAN NOT NULL DEFAULT FALSE,
  bounced_at          TIMESTAMPTZ,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE diagnostic_raters ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read diagnostic_raters"   ON diagnostic_raters;
DROP POLICY IF EXISTS "Allow anon insert diagnostic_raters" ON diagnostic_raters;
DROP POLICY IF EXISTS "Allow anon update diagnostic_raters" ON diagnostic_raters;
CREATE POLICY "Allow anon read diagnostic_raters"   ON diagnostic_raters FOR SELECT USING (true);
CREATE POLICY "Allow anon insert diagnostic_raters" ON diagnostic_raters FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update diagnostic_raters" ON diagnostic_raters FOR UPDATE USING (true);

COMMENT ON TABLE diagnostic_raters IS
  'One row per invited rater plus one row for the leader self-assessment (is_self=true).
   completed_at is visible to Alex only — never surfaced to the leader to preserve anonymity.
   Leader portal shows only name/relationship/invited_at, never completion status.';

COMMENT ON COLUMN diagnostic_raters.token IS
  'UUID token used in survey URL. Each rater gets a unique link.
   Example URL: /diagnostic-survey.html?token=<token>
   is_self=true tokens land the leader in self-report mode (Section E shown, Section F/G hidden).';


-- ── 4. diagnostic_responses — per question per rater ─────────────────────────
--
-- One row per question per rater. Rated questions use score, open-ended use
-- text_response. A few questions may use both (e.g. a 1-5 with a follow-up text).
--
-- question_code values:
--   Section A (Trust):       A1–A7 (rated), A8–A10 (open)
--   Section B (Proactivity): B1–B6 (rated), B7–B10 (open)
--   Section C (Productivity):C1–C6 (rated), C7–C9 (open)
--   Section D (Impact):      D1 (rated 1–10), D2 (open)
--   Section E (Succession):  E1–E5 (open, self-report only)
--   Section F (Bench):       F1–F2 (rated 1–5), F3 (open)
--   Section G (Custom):      G1 (rated 1–5, AI-generated per diagnostic)
--
-- Note: Section E responses are stored BOTH here (for completeness) AND as
-- denormalized columns on the diagnostics row (for fast Claude API access).

CREATE TABLE IF NOT EXISTS diagnostic_responses (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  diagnostic_id   UUID NOT NULL REFERENCES diagnostics(id) ON DELETE CASCADE,
  rater_id        UUID NOT NULL REFERENCES diagnostic_raters(id) ON DELETE CASCADE,

  question_code   TEXT NOT NULL,
  -- Format: letter + number, e.g. 'A1', 'B6', 'D1', 'G1', 'E3'

  score           NUMERIC(3,1),
  -- 1.0–5.0 for most rated questions (A1-A7, B1-B6, C1-C6, F1-F2, G1)
  -- 1.0–10.0 for D1 (Overall Impact)
  -- NULL for open-ended questions

  text_response   TEXT,
  -- Response text for open-ended questions
  -- NULL for pure rated questions

  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (rater_id, question_code)
  -- One answer per question per rater
);

ALTER TABLE diagnostic_responses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read diagnostic_responses"   ON diagnostic_responses;
DROP POLICY IF EXISTS "Allow anon insert diagnostic_responses" ON diagnostic_responses;
CREATE POLICY "Allow anon read diagnostic_responses"   ON diagnostic_responses FOR SELECT USING (true);
CREATE POLICY "Allow anon insert diagnostic_responses" ON diagnostic_responses FOR INSERT WITH CHECK (true);

COMMENT ON TABLE diagnostic_responses IS
  'One row per question per rater. Score for rated questions, text_response for open-ended.
   Section E (succession) responses also denormalized to diagnostics table for Claude API access.
   Never expose individual rater responses to the leader — only aggregated scores.';

COMMENT ON COLUMN diagnostic_responses.score IS
  'Numeric score. Scale depends on question:
   1–5: A1-A7, B1-B6, C1-C6, F1-F2, G1 (Strongly Disagree → Strongly Agree)
   1–10: D1 (Overall Leadership Impact)
   NULL: open-ended questions (A8-A10, B7-B10, C7-C9, D2, E1-E5, F3)';


-- ── 5. diagnostic_question_overrides — per-diagnostic customizations ──────────
--
-- Alex can edit the wording of any standard question for a specific diagnostic
-- (e.g. to match client context, industry, or language).
-- Overrides layer on top of the global question bank stored in code.

CREATE TABLE IF NOT EXISTS diagnostic_question_overrides (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  diagnostic_id   UUID NOT NULL REFERENCES diagnostics(id) ON DELETE CASCADE,
  question_code   TEXT NOT NULL,
  original_text   TEXT NOT NULL,
  override_text   TEXT NOT NULL,
  override_note   TEXT,
  -- Why this was changed — for Alex's reference
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (diagnostic_id, question_code)
);

ALTER TABLE diagnostic_question_overrides ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read diagnostic_question_overrides"   ON diagnostic_question_overrides;
DROP POLICY IF EXISTS "Allow anon insert diagnostic_question_overrides" ON diagnostic_question_overrides;
DROP POLICY IF EXISTS "Allow anon update diagnostic_question_overrides" ON diagnostic_question_overrides;
CREATE POLICY "Allow anon read diagnostic_question_overrides"   ON diagnostic_question_overrides FOR SELECT USING (true);
CREATE POLICY "Allow anon insert diagnostic_question_overrides" ON diagnostic_question_overrides FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update diagnostic_question_overrides" ON diagnostic_question_overrides FOR UPDATE USING (true);

COMMENT ON TABLE diagnostic_question_overrides IS
  'Per-diagnostic edits to standard question text. Survey fetches these and layers them
   over the global question bank. Only overridden questions have rows here — unmodified
   questions use the global bank text defined in code.';


-- ── 6. diagnostic_report_drafts — versioned AI-generated reports ──────────────
--
-- Each time Alex generates a report (via Claude API), a new version is saved here.
-- The highest version number with finalized_at IS NOT NULL is the active report.

CREATE TABLE IF NOT EXISTS diagnostic_report_drafts (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  diagnostic_id   UUID NOT NULL REFERENCES diagnostics(id) ON DELETE CASCADE,

  version         INTEGER NOT NULL DEFAULT 1,
  -- Increments on each generation

  -- Structured report content (JSON for section-by-section editing)
  content_json    JSONB,
  -- Keys: executive_summary, trust_section, proactivity_section,
  --       productivity_section, impact_section, succession_section,
  --       open_ended_themes, development_priorities, closing

  -- Full markdown (used for PDF/DOCX export)
  raw_markdown    TEXT,

  -- Claude prompt snapshot (for reproducibility and debugging)
  prompt_snapshot TEXT,

  generated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  finalized_at    TIMESTAMPTZ,
  -- Non-null = this version is the final report delivered to client

  finalized_by    TEXT DEFAULT 'alex@gpsleadership.org',

  UNIQUE (diagnostic_id, version)
);

ALTER TABLE diagnostic_report_drafts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon read diagnostic_report_drafts"   ON diagnostic_report_drafts;
DROP POLICY IF EXISTS "Allow anon insert diagnostic_report_drafts" ON diagnostic_report_drafts;
DROP POLICY IF EXISTS "Allow anon update diagnostic_report_drafts" ON diagnostic_report_drafts;
CREATE POLICY "Allow anon read diagnostic_report_drafts"   ON diagnostic_report_drafts FOR SELECT USING (true);
CREATE POLICY "Allow anon insert diagnostic_report_drafts" ON diagnostic_report_drafts FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update diagnostic_report_drafts" ON diagnostic_report_drafts FOR UPDATE USING (true);

COMMENT ON TABLE diagnostic_report_drafts IS
  'Versioned AI-generated report drafts. Each Claude API call creates a new version.
   finalized_at IS NOT NULL = this is the version delivered to the client.
   content_json allows section-by-section editing before finalization.';


-- ── 7. Indexes for performance ────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_diagnostics_client_id
  ON diagnostics (client_id);

CREATE INDEX IF NOT EXISTS idx_diagnostics_status
  ON diagnostics (status);

CREATE INDEX IF NOT EXISTS idx_diagnostics_close_date
  ON diagnostics (close_date)
  WHERE status = 'survey_open';
  -- Used by T-2 cron to find diagnostics closing soon

CREATE INDEX IF NOT EXISTS idx_diagnostics_leader_token
  ON diagnostics (leader_token);

CREATE INDEX IF NOT EXISTS idx_diagnostic_raters_diagnostic_id
  ON diagnostic_raters (diagnostic_id);

CREATE INDEX IF NOT EXISTS idx_diagnostic_raters_token
  ON diagnostic_raters (token);
  -- Critical: survey page looks up rater by token on every page load

CREATE INDEX IF NOT EXISTS idx_diagnostic_raters_completed
  ON diagnostic_raters (diagnostic_id, completed_at)
  WHERE completed_at IS NOT NULL;
  -- Used for response rate calculations

CREATE INDEX IF NOT EXISTS idx_diagnostic_responses_diagnostic
  ON diagnostic_responses (diagnostic_id);

CREATE INDEX IF NOT EXISTS idx_diagnostic_responses_rater
  ON diagnostic_responses (rater_id);

CREATE INDEX IF NOT EXISTS idx_diagnostic_responses_code
  ON diagnostic_responses (diagnostic_id, question_code);
  -- Used for per-question aggregate queries (avg A1 score, etc.)

CREATE INDEX IF NOT EXISTS idx_diagnostic_overrides_diagnostic
  ON diagnostic_question_overrides (diagnostic_id);

CREATE INDEX IF NOT EXISTS idx_diagnostic_report_drafts_diagnostic
  ON diagnostic_report_drafts (diagnostic_id, version DESC);


-- ── 8. ghl_export_view — safe GoHighLevel export ─────────────────────────────
--
-- Aggregates all scored diagnostic data into one flat row per diagnostic.
-- Used for periodic CSV export to GoHighLevel as off-system backup.
--
-- Fields prefixed gps_ per GHL custom field naming convention.
-- NEVER includes: verbatim text responses, individual rater scores,
-- successor self-report responses, or rater email addresses.
--
-- Score computation:
--   Trust Index     = avg(A1–A7) from non-self raters
--   Proactivity     = avg(B1–B6) from non-self raters
--   Productivity    = avg(C1–C6) from non-self raters
--   TP3 Index       = (Trust + Proactivity + Productivity) / 3
--   Overall Impact  = avg(D1) from non-self raters (1–10 scale)
--   Succession F1   = avg(F1) from non-self raters
--   Succession F2   = avg(F2) from non-self raters
--   G1 Custom       = avg(G1) from non-self raters
--   Self Trust      = avg(A1–A7) from self rater only
--   Self Proactivity= avg(B1–B6) from self rater only
--   Self Productivity=avg(C1–C6) from self rater only

CREATE OR REPLACE VIEW ghl_export_view AS
WITH rater_scores AS (
  -- Aggregate all rated question scores per diagnostic, excluding self
  SELECT
    dr.diagnostic_id,
    AVG(CASE WHEN drs.question_code IN ('A1','A2','A3','A4','A5','A6','A7') THEN drs.score END) AS trust_others,
    AVG(CASE WHEN drs.question_code IN ('B1','B2','B3','B4','B5','B6')      THEN drs.score END) AS proactivity_others,
    AVG(CASE WHEN drs.question_code IN ('C1','C2','C3','C4','C5','C6')      THEN drs.score END) AS productivity_others,
    AVG(CASE WHEN drs.question_code = 'D1'                                  THEN drs.score END) AS overall_impact,
    AVG(CASE WHEN drs.question_code = 'F1'                                  THEN drs.score END) AS succession_f1,
    AVG(CASE WHEN drs.question_code = 'F2'                                  THEN drs.score END) AS succession_f2,
    AVG(CASE WHEN drs.question_code = 'G1'                                  THEN drs.score END) AS succession_g1
  FROM diagnostic_raters dr
  JOIN diagnostic_responses drs ON drs.rater_id = dr.id
  WHERE dr.is_self = FALSE
    AND dr.completed_at IS NOT NULL
  GROUP BY dr.diagnostic_id
),
self_scores AS (
  -- Self-report scores only
  SELECT
    dr.diagnostic_id,
    AVG(CASE WHEN drs.question_code IN ('A1','A2','A3','A4','A5','A6','A7') THEN drs.score END) AS self_trust,
    AVG(CASE WHEN drs.question_code IN ('B1','B2','B3','B4','B5','B6')      THEN drs.score END) AS self_proactivity,
    AVG(CASE WHEN drs.question_code IN ('C1','C2','C3','C4','C5','C6')      THEN drs.score END) AS self_productivity
  FROM diagnostic_raters dr
  JOIN diagnostic_responses drs ON drs.rater_id = dr.id
  WHERE dr.is_self = TRUE
    AND dr.completed_at IS NOT NULL
  GROUP BY dr.diagnostic_id
),
rater_counts AS (
  SELECT
    diagnostic_id,
    COUNT(*) FILTER (WHERE is_self = FALSE)                   AS total_invited,
    COUNT(*) FILTER (WHERE is_self = FALSE AND completed_at IS NOT NULL) AS total_completed
  FROM diagnostic_raters
  GROUP BY diagnostic_id
)
SELECT
  d.id                    AS diagnostic_id,
  d.client_name           AS gps_contact_name,
  d.client_email          AS gps_contact_email,
  d.client_title          AS gps_role_title,
  d.client_org            AS gps_company,
  d.tier                  AS gps_diagnostic_tier,
  d.status                AS gps_diagnostic_status,
  d.start_date            AS gps_survey_start,
  d.close_date            AS gps_survey_close,
  d.debrief_completed_at  AS gps_debrief_date,
  d.plan_status           AS gps_plan_status,
  d.created_at            AS gps_diagnostic_created,

  -- Response stats
  rc.total_invited        AS gps_raters_invited,
  rc.total_completed      AS gps_raters_completed,
  ROUND(rc.total_completed::NUMERIC / NULLIF(rc.total_invited,0) * 100, 1)
                          AS gps_response_rate_pct,

  -- TP3 Scores (Others only, rounded to 2 decimal places)
  ROUND(rs.trust_others::NUMERIC, 2)       AS gps_trust_score,
  ROUND(rs.proactivity_others::NUMERIC, 2) AS gps_proactivity_score,
  ROUND(rs.productivity_others::NUMERIC, 2)AS gps_productivity_score,
  ROUND(((rs.trust_others + rs.proactivity_others + rs.productivity_others) / 3.0)::NUMERIC, 2)
                                           AS gps_tp3_index,
  ROUND(rs.overall_impact::NUMERIC, 2)     AS gps_overall_impact,

  -- Succession scores
  ROUND(rs.succession_f1::NUMERIC, 2)      AS gps_succession_f1,
  ROUND(rs.succession_f2::NUMERIC, 2)      AS gps_succession_f2,
  ROUND(rs.succession_g1::NUMERIC, 2)      AS gps_succession_g1_custom,

  -- Self-report scores (shown separately, never blended into TP3)
  ROUND(ss.self_trust::NUMERIC, 2)         AS gps_self_trust,
  ROUND(ss.self_proactivity::NUMERIC, 2)   AS gps_self_proactivity,
  ROUND(ss.self_productivity::NUMERIC, 2)  AS gps_self_productivity

FROM diagnostics d
LEFT JOIN rater_scores rs ON rs.diagnostic_id = d.id
LEFT JOIN self_scores  ss ON ss.diagnostic_id = d.id
LEFT JOIN rater_counts rc ON rc.diagnostic_id = d.id
ORDER BY d.created_at DESC;

COMMENT ON VIEW ghl_export_view IS
  'Flat aggregated view for GoHighLevel CSV export. Safe to share externally —
   contains NO verbatim responses, NO individual rater data, NO successor names.
   All score fields prefixed gps_ for GHL custom field naming convention.
   Run: SELECT * FROM ghl_export_view; then export as CSV.';


-- ── 9. updated_at trigger ─────────────────────────────────────────────────────
--
-- Keeps diagnostics.updated_at current on every row change.

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_diagnostics_updated_at ON diagnostics;
CREATE TRIGGER set_diagnostics_updated_at
  BEFORE UPDATE ON diagnostics
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS set_overrides_updated_at ON diagnostic_question_overrides;
CREATE TRIGGER set_overrides_updated_at
  BEFORE UPDATE ON diagnostic_question_overrides
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ── Done ─────────────────────────────────────────────────────────────────────
--
-- Next: supabase-migration-v14.sql will add diagnostic email templates
-- (invite, reminder_1, reminder_2, t2_alert, report_ready, plan_locked)
-- to the existing email_templates table.
--
-- File summary:
--   diagnostics                    : core engagement record
--   diagnostic_raters              : one per invited person (incl. self)
--   diagnostic_responses           : one per question per rater
--   diagnostic_question_overrides  : per-diagnostic question edits
--   diagnostic_report_drafts       : versioned AI-generated reports
--   ghl_export_view                : safe aggregated export for GHL
